# Generated by Django 3.1.1 on 2020-09-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuggestAdjectives', '0002_auto_20200922_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(max_length=200, verbose_name='word')),
                ('synonyms', models.ManyToManyField(related_name='_adjective_synonyms_+', to='SuggestAdjectives.Adjective')),
            ],
        ),
    ]
