# Generated by Django 3.1.1 on 2020-10-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuggestAdjectives', '0003_adjective'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(max_length=200, verbose_name='word')),
            ],
        ),
    ]
