# Generated by Django 3.1.1 on 2020-10-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuggestAdjectives', '0004_wordcontext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordContext',
        ),
        migrations.AddField(
            model_name='adjective',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='is crawled?'),
        ),
    ]
